import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const read = (path) => readFile(join(root, path), "utf8");
const normalized = (content) => content.replace(/\r\n/g, "\n");
const channelArgument = process.argv.find((value) => value.startsWith("--channel="));
const channel = channelArgument?.split("=")[1] ?? "stable";
const metadataPath = channel === "beta" ? "public/beta-version.json" : "public/version.json";
const metadata = JSON.parse(await read(metadataPath));

if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(metadata.version) || !Number.isInteger(metadata.build)) {
  throw new Error(`${metadataPath} must declare a semantic version and integer build.`);
}

for (const language of ["zh", "en"]) {
  if (!Array.isArray(metadata.inAppReleaseNotes?.[language]) ||
      metadata.inAppReleaseNotes[language].length === 0) {
    throw new Error(`Missing inAppReleaseNotes.${language}`);
  }
  if (!Array.isArray(metadata.releaseNoteSections?.[language]) ||
      metadata.releaseNoteSections[language].length === 0) {
    throw new Error(`Missing releaseNoteSections.${language}`);
  }
}

const dartList = (items) =>
  items.map((item) => `  ${JSON.stringify(item)},`).join("\n");
const generatedAppVersion = `// Generated by tool/sync_release_metadata.mjs.
// Edit ${metadataPath}, then rerun the sync tool.
const appVersion = ${JSON.stringify(metadata.version)};
const appBuildNumber = ${metadata.build};

const releaseNotesZh = <String>[
${dartList(metadata.inAppReleaseNotes.zh)}
];

const releaseNotesEn = <String>[
${dartList(metadata.inAppReleaseNotes.en)}
];
`;

const appVersionPath = join(root, "apps/lexora/lib/app_version.dart");
const currentAppVersion = await readFile(appVersionPath, "utf8");
if (checkOnly) {
  if (normalized(currentAppVersion) !== normalized(generatedAppVersion)) {
    throw new Error("apps/lexora/lib/app_version.dart is out of sync.");
  }
} else {
  await writeFile(appVersionPath, generatedAppVersion);
}

const renderSections = (language) =>
  metadata.releaseNoteSections[language]
    .map(
      (section) =>
        `### ${section.title}\n\n${section.items
          .map((item) => `- ${item}`)
          .join("\n")}`,
    )
    .join("\n\n");

async function synchronizeReadme(path, language) {
  const marker = new RegExp(
    `<!-- release-notes:${language}:start -->[\\s\\S]*?<!-- release-notes:${language}:end -->`,
  );
  const start = `<!-- release-notes:${language}:start -->`;
  const end = `<!-- release-notes:${language}:end -->`;
  let next = await read(path);
  next = next.replace(marker, `${start}\n\n${renderSections(language)}\n\n${end}`);
  next = next.replace(
    language === "zh"
      ? /## Lexora \d+\.\d+\.\d+ 更新说明/
      : /## Lexora \d+\.\d+\.\d+ release notes/,
    language === "zh"
      ? `## Lexora ${metadata.version} 更新说明`
      : `## Lexora ${metadata.version} release notes`,
  );
  for (const [platform, download] of Object.entries(metadata.verifiedDownloads)) {
    const extension =
      platform === "windows"
        ? "-setup\\.exe"
        : platform === "android"
          ? "\\.apk"
          : platform === "macos"
            ? "\\.dmg"
            : "\\.tar\\.gz";
    next = next.replace(
      new RegExp(`lexora-${platform}-v\\d+\\.\\d+\\.\\d+${extension}`, "g"),
      download.filename,
    );
  }
  const current = await read(path);
  if (checkOnly) {
    if (normalized(current) !== normalized(next)) {
      throw new Error(`${path} is out of sync.`);
    }
  } else if (current !== next) {
    await writeFile(join(root, path), next);
  }
  return next;
}

const readmes = channel === "stable"
  ? {
      "README.md": await synchronizeReadme("README.md", "zh"),
      "README.en.md": await synchronizeReadme("README.en.md", "en"),
    }
  : {};

const pubspec = await read("apps/lexora/pubspec.yaml");
if (!pubspec.includes(`version: ${metadata.version}+${metadata.build}`)) {
  throw new Error(`Flutter pubspec version does not match ${metadataPath}.`);
}

const expectedFiles = Object.values(metadata.verifiedDownloads).map(
  (download) => download.filename,
);
for (const readmePath of channel === "stable" ? ["README.md", "README.en.md"] : []) {
  const readme = readmes[readmePath];
  for (const filename of expectedFiles) {
    if (!readme.includes(filename)) {
      throw new Error(`${readmePath} does not link ${filename}.`);
    }
  }
}

const website = await read("app/page.tsx");
if (!website.includes('from "../public/version.json"') ||
    !website.includes('from "../public/beta-version.json"')) {
  throw new Error("Website must import stable and beta release manifests.");
}

const windowsInstaller = await read("apps/lexora/packaging/windows/lexora.iss");
if (channel === "stable" && (!windowsInstaller.includes(`#define AppVersion "${metadata.version}"`) ||
    !windowsInstaller.includes('"lexora-windows-v" + AppVersion + "-setup"'))) {
  throw new Error("Windows installer defaults are out of sync.");
}

const macSource = await read("apps/lexora/packaging/macos/MainFlutterWindow.swift");
if (!macSource.includes('CFBundleShortVersionString')) {
  throw new Error("macOS sidebar must read the bundle version dynamically.");
}

console.log(
  checkOnly
    ? `Lexora ${metadata.version}+${metadata.build} metadata is synchronized.`
    : `Generated Lexora ${metadata.version}+${metadata.build} app metadata.`,
);
