// Generated by tool/sync_release_metadata.mjs.
// Edit public/beta-version.json, then rerun the sync tool.
const appVersion = "4.1.0-beta.4";
const appBuildNumber = 32;

const releaseNotesZh = <String>[
  "修复 Android 底栏快速点击时可能误跳到学习页面的问题。",
  "学习页六个入口移到顶部，并改为单行横向导航。",
  "优化小屏幕的选中项定位、设置标题排版与点击反馈。",
];

const releaseNotesEn = <String>[
  "Fixes Android bottom-navigation taps that could incorrectly open Learning.",
  "Moves all six Learning destinations into one horizontal top bar.",
  "Improves selected-tab positioning, narrow Settings layout, and touch feedback.",
];
