// Generated by tool/sync_release_metadata.mjs.
// Edit public/version.json, then rerun the sync tool.
const appVersion = "4.0.3";
const appBuildNumber = 28;

const releaseNotesZh = <String>[
  "修复设置页按压遮罩的方形边缘，圆角现在与卡片边界一致。",
  "加快单词预览弹窗的打开、展开与关闭动画，拖拽反馈更加跟手。",
  "修复联想面板左右边缘不一致和窄屏越界的问题。",
];

const releaseNotesEn = <String>[
  "Fixed square press overlays in Settings so their corners now match the surrounding cards.",
  "Sped up word-preview opening, expansion, and dismissal for more direct drag feedback.",
  "Fixed uneven suggestion-panel edges and narrow-screen overflow.",
];
