// Generated by tool/sync_release_metadata.mjs.
// Edit public/version.json, then rerun the sync tool.
const appVersion = "4.0.0";
const appBuildNumber = 25;

const releaseNotesZh = <String>[
  "更快的词典搜索和联想预加载，常用单词可更快显示核心结果。",
  "新增完整词典页面、搜索历史和一键加入个人词汇书。",
  "优化词汇书生成、文档预览、历史管理与跨页面操作。",
  "全面改善 Android、macOS、Windows 和 Linux 端的稳定性。",
  "重新优化软件和官网动画，拖拽、搜索和窗口缩放更加流畅。",
  "修复已发现的崩溃、更新、音标、键盘和界面显示问题。",
];

const releaseNotesEn = <String>[
  "Faster dictionary search and suggestion preloading for quicker core results.",
  "A complete dictionary experience with search history and one-tap vocabulary-book saving.",
  "Improved vocabulary-book generation, document viewing, history management, and navigation.",
  "Better stability across Android, macOS, Windows, and Linux.",
  "Smoother animations for search, dragging, navigation, and desktop resizing.",
  "Fixes for crashes, updates, phonetics, keyboards, and interface issues.",
];
